print("this is \\\\  double backslash")
print("these are /\/\/\/\ mountains")
print("he is \t awesome")
print("\\\"\\n \\t \\\'")
print(r"hello world\nhello broo")
print("\U0001F602"+ "  wtf")
print(2+2)
print(2+3**5/66)
print(round(2**0.5, 4)
name = "shajid"
last_name = "rayhan"
full_name = name + " " + last_name
print(full_name)                                                              # some random code.. :)
name = input("type your name") 
print("hello " + name)
name, age = "shajid", 24
name, age = input("input yopur name and age wiht a spae").split()
print("hello " + name + "your age is " + str(age))
name, age, age = input("input your name and age ").split()
print(name, age)
name, age = input("input yopur name and age wiht a spae").split()
name, age = input("hello world input your name and age with a space ").split()
print(f"hello {name} your age is {age}") #clean string formatting
number1, number2, number3 = input("input 3 number with a space if you need to avarage number for thos input ").split()
print(f"hi your avrage number is {int(number1) + int(number2) + int(number3)}")
name = "hello world"
print(name[0:])
print(len(name))
print("shjaidryahan"[:8:-7])
name = input("enter your name : ")
print(name[-1::-1])
name , car = input("enter your name : ").split()
print(f"name of your lent is {len(name)}")
print(f"character count : {name.count(car)}")
name, car = input("give youur name and a car to count but with a space").split()
print(f"lent of your name is : {len(name)}")
name = (f"{name.lower()}{name.upper()}")
print(f"your name have : {name.count(car)} caracter")
name, car = input("enter your name and car").split()
print(f"your name length is : {len(name)}")
name = (f"{name.lower()}{name.upper()}")
print(f"your name have : {name.strip().count(car.strip())}")
name, car = input("input your name and car : ").split()
print(f"lenth of your name is {len(name)}")
name = (f"{name.lower()}{name.upper()}")
print(f"your name have {name.strip().count(car.strip())}")
name = ("Shjaid is a bad boy")
print(name.find("is"))
name = input("inter your name")
print(name.center(len(name)+16, "*"))
string is immutable/////    string paltan no jay